### PR TITLE
Empty bank deck

### PR DESCRIPTION
**Pull request by MidnightBlackHorse17**

### CODE REVIEW

**Review by rastguelenianrn — COMMENTED** [review]
Looks good! Not sure if it matters but did you use CardGames.py at all?

**Review by rastguelenianrn — APPROVED** [review]
Sorry, had to leave this second comment to approve it!

**Comment by MidnightBlackHorse17** [comment]
> Looks good! Not sure if it matters but did you use CardGames.py at all?

I didn't really need to use it, but I put a function in there to check if the deck is empty. Thanks!

**Comment by psk44** [comment]
I reviewed the code and everything looked good to me!

**Comment by psk44** [comment]
I approve lol

**Pull request merged**
