### PR TITLE
Joanna

### PR DESCRIPTION
**Pull request by MidnightBlackHorse17**

### CODE REVIEW

**Comment by rastguelenianrn** [comment]
Looks good, I see where it iterates through each player and lists their name, but is the code for printing each player's known cards + money included in the commit? I couldnt find it there

**Comment by MidnightBlackHorse17** [comment]
I believe it is included in the commit.. You would want to check the responses recorded on the PyTest upload for the results. I generated the tests with the base case of each player having no cards or money yet.

**Review by rastguelenianrn — APPROVED** [review]

**Comment by psk44** [comment]
The code seems to work and is simple to understand. Maybe you could add a display for the hand if you'd like?

**Comment by MidnightBlackHorse17** [comment]
Thanks for your feedback! I actually omitted the display for the hand because we haven't established the game scenario yet (whether we should display the hand or not depends on the game scenario). Once the scenario is set, the necessary changes can be made. Let me know if you have any other questions!

**Pull request merged**
